# Generated by Django 4.0.6 on 2022-07-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='booking_amount',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='total_project_value',
        ),
    ]
